title: Driving Cognition Lab
description: Decoding Driver Decisions.
remote_theme: pmarsceill/just-the-docs

# Appearance
color_scheme: "light"
aux_links:
  "GitHub": "https://github.com/Drivingsimulation/driving-cognition-lab"
# Logo Setup
logo: "/logo.png"

# Optional: If you want the logo to link back to the home page
logo_link: "/"
# This helps with space and layout
nav_config:
  - title: About Our Lab
    url: /
  - title: Research Projects
    url: /projects/
  - title: Driving Simulator
    url: /simulator/
  - title: People
    url: /people/
  - title: Contact
    url: /contact/

    # Tells the site to use your custom CSS
scss:
  load_paths: ["_sass"]

# Ensure the site knows where the main CSS is
aux_links:
  "Back to Top": "#"
