title: Driving Cognition Lab
tagline: Decoding Driver Decisions.
description: Lab website for driving cognition research.

# Theme Settings
theme: jekyll-theme-chirpy
remote_theme: cotes2020/jekyll-theme-chirpy

# This must match your GitHub URL exactly
url: 'https://Drivingsimulation.github.io'
baseurl: '/driving-cognition-lab'

# This tells the theme where your logo is
avatar: '/logo.png'

plugins:
  - jekyll-remote-theme
