title: Driving Cognition Lab
tagline: Decoding Driver Decisions.
description: Lab website for driving cognition research.

# Theme Settings
remote_theme: cotes2020/jekyll-theme-chirpy
jekyll-theme-chirpy:
  assets:
    self_hosted: true

# Navigation Settings
url: 'https://Drivingsimulation.github.io'
baseurl: '/driving-cognition-lab' # This must match your repo name exactly

# Logo
avatar: '/logo.png'

# Plugins
plugins:
  - jekyll-theme-chirpy
